USE alx_book_store;  
  
SELECT  
  COLUMN_NAME,  
  DATA_TYPE,  
  CHARACTER_MAXIMUM_LENGTH,  
  NUMERIC_PRECISION,  
  NUMERIC_SCALE,  
  COLUMN_DEFAULT,  
  IS_NULLABLE,  
  COLUMN_KEY,  
  EXTRA  
FROM  
  INFORMATION_SCHEMA.COLUMNS  
WHERE  
  TABLE_NAME = 'books' AND TABLE_SCHEMA = 'alx_book_store';

